/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-06-09 07:38:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import member.dto.MemberDTO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1749454716000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("member.dto.MemberDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title> 투어리스트인투어 </title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/swiper.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"js/rollmain.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.easing.js\"></script>	\r\n");
      out.write("<script src=\"js/common.js\"></script>  \r\n");
      out.write("<script src=\"js/jquery.smooth-scroll.min.js\"></script> \r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("	<script src=\"js/placeholders.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"skipnavi\">\r\n");
      out.write("    <li><a href=\"#container\">본문내용</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- wrap -->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("		<div class=\"header_area box_inner clear\">	\r\n");
      out.write("			<h1><a href=\"./\">Tourist in tour</a></h1>\r\n");
      out.write("			<p class=\"openMOgnb\"><a href=\"#\"><b class=\"hdd\">메뉴열기</b> <span></span><span></span><span></span></a></p>\r\n");
      out.write("			<!-- header_cont -->\r\n");
      out.write("			<div class=\"header_cont\">\r\n");
      out.write("				<ul class=\"util clear\">\r\n");
      out.write("					");
if(session.getAttribute("userDTO")!=null){ 
      out.write("\r\n");
      out.write("					<li>\r\n");
      out.write("						<span style=\"color:white;\">\r\n");
      out.write("						");
      out.print(((MemberDTO)session.getAttribute("userDTO")).getName() );
      out.write("님 환영합니다.\r\n");
      out.write("						</span>\r\n");
      out.write("					</li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("					<li>\r\n");
      out.write("						");
if(session.getAttribute("userDTO")==null){ 
      out.write("\r\n");
      out.write("							<a href=\"./login.do\">로그인</a>\r\n");
      out.write("						");
}else{ 
      out.write("\r\n");
      out.write("							<a href=\"./logout.do\">로그아웃</a>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"./join.do\">회원가입</a></li>\r\n");
      out.write("				</ul>		\r\n");
      out.write("				<nav>\r\n");
      out.write("				<ul class=\"gnb clear\">\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll1\">여행정보</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_1\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">국내</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">해외</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll2\">고객센터</a>\r\n");
      out.write("				        <div class=\"gnb_depth gnb_depth2_2\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"./boardlist.do\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">문의하기</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll3\">상품투어</a>\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_3\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"/program.do\">프로그램 소개</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">여행자료</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"openAll4\">티켓/가이드</a>\r\n");
      out.write("                        <div class=\"gnb_depth gnb_depth2_4\">\r\n");
      out.write("                            <ul class=\"submenu_list\">\r\n");
      out.write("                                <li><a href=\"javascript:;\">항공</a></li>\r\n");
      out.write("                                <li><a href=\"javascript:;\">호텔</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("				<p class=\"closePop\"><a href=\"javascript:;\">닫기</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //header_cont -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("        <div class=\"main_rolling_pc\">\r\n");
      out.write("            <div class=\"visualRoll\">\r\n");
      out.write("                <ul class=\"viewImgList\">\r\n");
      out.write("                    <li class=\"imglist0\">\r\n");
      out.write("                        <div class=\"roll_content\">\r\n");
      out.write("                            <a href=\"javascript:;\">\r\n");
      out.write("                            <img src=\"img/img_slidecontents01.png\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\"></a>\r\n");
      out.write("                            <p class=\"roll_txtline\">BE TOURIST FOR BETTER LIFE</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"imglist1\">\r\n");
      out.write("                        <div class=\"roll_content\">\r\n");
      out.write("                            <a href=\"javascript:;\">\r\n");
      out.write("                            <img src=\"img/img_slidecontents02.png\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\"></a>\r\n");
      out.write("                            <p class=\"roll_txtline\">BE TOURIST FOR BETTER LIFE</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"imglist2\">\r\n");
      out.write("                        <div class=\"roll_content\">\r\n");
      out.write("                            <a href=\"javascript:;\">\r\n");
      out.write("                            <img src=\"img/img_slidecontents03.png\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\"></a>\r\n");
      out.write("                            <p class=\"roll_txtline\">BE TOURIST FOR BETTER LIFE</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"rollbtnArea\">\r\n");
      out.write("                    <ul class=\"rollingbtn\">\r\n");
      out.write("                        <li class=\"seq butt0\"><a href=\"#butt\"><img src=\"img/btn_rollbutt_on.png\" alt=\"1번\" /></a></li>\r\n");
      out.write("                        <li class=\"seq butt1\"><a href=\"#butt\"><img src=\"img/btn_rollbutt_off.png\" alt=\"2번\" /></a></li>\r\n");
      out.write("                        <li class=\"seq butt2\"><a href=\"#butt\"><img src=\"img/btn_rollbutt_off.png\" alt=\"3번\" /></a></li>\r\n");
      out.write("                        <li class=\"rollstop\"><a href=\"#\" class=\"stop\"><img src=\"img/btn_roll_stop.png\" alt=\"멈춤\" /></a></li>\r\n");
      out.write("                        <li class=\"rollplay\"><a href=\"#\" class=\"play\"><img src=\"img/btn_roll_play.png\" alt=\"재생\" /></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- //rollbtnArea -->\r\n");
      out.write("\r\n");
      out.write("            </div><!-- //visualRoll -->\r\n");
      out.write("        </div><!-- //main_rolling_pc -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"main_rolling_mobile\">\r\n");
      out.write("            <div class=\"swiper-container\">\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <a href=\"javascript:;\"><img src=\"img/mainslide_mob01.jpg\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <a href=\"javascript:;\"><img src=\"img/mainslide_mob02.jpg\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <a href=\"javascript:;\"><img src=\"img/mainslide_mob03.jpg\" alt=\"TRUST & INFORMATION 믿을 수 있는 여행정보, 여행... 어디로 가세요?\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>						\r\n");
      out.write("                <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                <!-- <div class=\"swiper-button-next\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev\"></div> -->\r\n");
      out.write("                \r\n");
      out.write("            </div><!--//swiper-container-->\r\n");
      out.write("        </div><!--//main_rolling_mobile -->\r\n");
      out.write("	\r\n");
      out.write("		<!-- about_area -->\r\n");
      out.write("		<div class=\"about_area\">\r\n");
      out.write("			<h2>다시 찾는 인기 여행지 <b>TOP 3</b></h2>\r\n");
      out.write("			<div class=\"about_box\">\r\n");
      out.write("				<ul class=\"place_list box_inner clear\">\r\n");
      out.write("					<li><a href=\"#\" onclick=\"$('.popup_base').css('height',$(document).height());$('.contact_pop').show();\">\r\n");
      out.write("							<img class=\"img_topplace\" src=\"img/img_topplace01.jpg\" alt=\"다리를 높이 들어 운동\" />\r\n");
      out.write("							<h3>성패트릭 대성당</h3>\r\n");
      out.write("							<p class=\"txt\">바쁜 뉴욕 안에서 정교하면서도 웅장한 기운에 침묵하게 되는 기도의 시간!</p>\r\n");
      out.write("							<span class=\"view\">VIEW</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"#\" onclick=\"$('.popup_base').css('height',$(document).height());$('.space_pop').show();\">\r\n");
      out.write("							<img class=\"img_topplace\" src=\"img/img_topplace02.jpg\" alt=\"바닷가에서 스트레칭\" />\r\n");
      out.write("							<h3>원주 뮤지엄 '산'</h3>\r\n");
      out.write("							<p class=\"txt\">전시된 유산들을 담아낸 건물에 신비로운 돌과 물의 테마가 담겨 있다.</p>\r\n");
      out.write("							<span class=\"view\">VIEW</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"#\" onclick=\"$('.popup_base').css('height',$(document).height());$('.program_pop').show();\">\r\n");
      out.write("							<img class=\"img_topplace\" src=\"img/img_topplace03.jpg\" alt=\"앉아서 스트레칭\" />\r\n");
      out.write("							<h3>일본 만국박람회 기념공원</h3>\r\n");
      out.write("							<p class=\"txt\">오사카 센리 반파쿠에는 드넓은 대지에 정원과 들, 물과 함께 하는 문화가 있다.</p>\r\n");
      out.write("							<span class=\"view\">VIEW</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //about_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- app_area -->\r\n");
      out.write("		<div class=\"appbbs_area\">\r\n");
      out.write("			<div class=\"appbbs_box box_inner clear\">\r\n");
      out.write("				<h2 class=\"hdd\">상담과 최근게시물</h2>\r\n");
      out.write("				<p class=\"app_line\">\r\n");
      out.write("					<a href=\"javascript:;\">카카오톡 1:1 상담</a>\r\n");
      out.write("					<a href=\"javascript:;\">전화 상담 신청</a>\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"bbs_line\">\r\n");
      out.write("					<h3>NOTICE</h3>\r\n");
      out.write("					<ul class=\"notice_recent\">\r\n");
      out.write("						<li><a href=\"javascript:;\">이번 여름 휴가 제주 갈까? 미션 투어 (여행경비 50만원 지원)</a></li>\r\n");
      out.write("						<li><a href=\"javascript:;\">박물관 미션 투어 응모 당첨자 발표</a></li>\r\n");
      out.write("						<li><a href=\"javascript:;\">추석 연휴 티켓/투어 배송 및 직접 수령 안내</a></li>\r\n");
      out.write("						<li><a href=\"javascript:;\">하롱베이 서비스 OPEN! (여행정보, 가이드북, 가이드맵)</a></li>\r\n");
      out.write("						<li><a href=\"javascript:;\">투어리스트인투어 서비스 점검 안내</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //app_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"foot_area box_inner\">\r\n");
      out.write("			<ul class=\"foot_list clear\">\r\n");
      out.write("				<li><a href=\"javascript:;\">이용약관</a></li>\r\n");
      out.write("				<li><a href=\"javascript:;\">개인정보취급방침</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<h2>투어리스트인투어</h2>\r\n");
      out.write("            <p class=\"addr\">서울특별시 종로구 혜화동 9길 청운빌딩 5층 <span class=\"gubun\">/</span>        \r\n");
      out.write("				<span class=\"br_line\">대표전화 <span class=\"space0\">02-1234-5678</span> <span class=\"gubun\">/</span>        \r\n");
      out.write("					<span class=\"br_line\">E-mail : <span class=\"space0\"> titour@touristintour.com</span></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p class=\"copy box_inner\">Copyright(c) TouristInTour all right reserved</p>\r\n");
      out.write("			<ul class=\"snslink clear\">\r\n");
      out.write("				<li><a href=\"javascript:;\">blog</a></li>\r\n");
      out.write("				<li><a href=\"javascript:;\">facebook</a></li>\r\n");
      out.write("				<li><a href=\"javascript:;\">instargram</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrap -->\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"hdd\">빠른 링크 : 전화 문의,카카오톡,오시는 길,꼭대기로</h2>\r\n");
      out.write("<div class=\"quick_area\">\r\n");
      out.write("	<ul class=\"quick_list\">\r\n");
      out.write("		<li><a href=\"tel:010-7184-4403\"><h3>전화 문의</h3><p>010-1234-5678</p></a></li>\r\n");
      out.write("		<li><a href=\"javascript:;\"><h3>카카오톡 <em>상담</em></h3><p>1:1상담</p></a></li>\r\n");
      out.write("		<li><a href=\"javascript:;\"><h3 class=\"to_contact\">오시는 길</h3></a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<p class=\"to_top\"><a href=\"#layout0\" class=\"s_point\">TOP</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/swiper.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("		var swiper = new Swiper('.swiper-container', {\r\n");
      out.write("			loop: true,\r\n");
      out.write("			autoplay:5500,\r\n");
      out.write("		    autoplayDisableOnInteraction: false,\r\n");
      out.write("			pagination: '.swiper-pagination',\r\n");
      out.write("            paginationClickable: true\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- contact_pop -->\r\n");
      out.write("<div class=\"popup_base contact_pop\">\r\n");
      out.write("	<div class=\"pop_content\">\r\n");
      out.write("		<p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("		<ul class=\"pop_list\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<h2 class=\"tit_pop\">성패트릭 대성당</h2>\r\n");
      out.write("				<img class=\"pop_img\"src=\"img/img_pop1_1.jpg\" alt=\"성패트릭 대성당\" />\r\n");
      out.write("				<div class=\"pop_txt\"><p>뉴욕에서 만난 아름다운 고딕양식에 감탄을 금할 수 없습니다. <br>인상적인 예술작품들과 함께 하고 있으며 정교한 구조와 섬세한 조각들을 만날 수 있습니다. </p></div>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //contact_pop -->\r\n");
      out.write("\r\n");
      out.write("<!-- space_pop -->\r\n");
      out.write("<div class=\"popup_base space_pop\">\r\n");
      out.write("	<div class=\"pop_content\">\r\n");
      out.write("		<p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("		<ul class=\"pop_list\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<h2 class=\"tit_pop\">원주 뮤지엄 '산'</h2>\r\n");
      out.write("				<img class=\"pop_img\"src=\"img/img_pop2_1.jpg\" alt=\"뮤지엄 산의 물위의 건물\" />\r\n");
      out.write("				<div class=\"pop_txt\"><p>실내와 야외, 문화와 자연이 공존하는 세계. <br> 뮤지엄 산은  휴식과 소통이 어울러진 복합공간을 추구합니다. </p></div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<h2 class=\"tit_pop\">박물관 야외</h2>\r\n");
      out.write("				<img class=\"pop_img\"src=\"img/img_pop2_2.jpg\" alt=\"박물관 야외조경\" />\r\n");
      out.write("				<div class=\"pop_txt\"><p>공간에 대한 관람을 최대한 배려하려고 합니다.<br>뮤지엄 산은 돌과 물과 산이 함께 어울림으로 배치된 조형 공간입니다.</p></div>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //space_pop -->\r\n");
      out.write("\r\n");
      out.write("<!-- program_pop -->\r\n");
      out.write("<div class=\"popup_base program_pop\">\r\n");
      out.write("	<div class=\"pop_content\">\r\n");
      out.write("		<p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("		<ul class=\"pop_list\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<h2 class=\"tit_pop\">일본 만국박람회 기념 공원</h2>\r\n");
      out.write("				<img class=\"pop_img\"src=\"img/img_pop3_1.jpg\" alt=\"일본 만국박람회 기념 공원\" />\r\n");
      out.write("				<div class=\"pop_txt\"><p>센리 반파쿠 기념 공원에서는 일본 정원의 확장판을 만날 수 있습니다.<br>가능한 가장 넓은 공간에 꾸민 연못, 산림욕, 정원, 산책길을 만끽할 수 있습니다.</p></div>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //program_pop -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
