/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-06-09 07:39:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title> 회원가입 | 투어리스트인투어 </title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"js/common.js\"></script>  \r\n");
      out.write("<script src=\"js/jquery.smooth-scroll.min.js\"></script> \r\n");
      out.write("<!--[if lte IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("	<script src=\"js/placeholders.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"skipnavi\">\r\n");
      out.write("    <li><a href=\"#container\">본문내용</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<!-- wrap -->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<!-- location_area -->\r\n");
      out.write("		<div class=\"location_area member\">\r\n");
      out.write("			<div class=\"box_inner\">\r\n");
      out.write("				<h2 class=\"tit_page\">TOURIST <span class=\"in\">in</span> TOUR</h2>\r\n");
      out.write("				<p class=\"location\">MEMBER <span class=\"path\">/</span> 회원가입</p>\r\n");
      out.write("				<ul class=\"page_menu clear\">\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"on\">회원가입</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<!-- //location_area -->\r\n");
      out.write("\r\n");
      out.write("		<!-- bodytext_area -->\r\n");
      out.write("		<div class=\"bodytext_area box_inner\">\r\n");
      out.write("			<!-- appForm -->\r\n");
      out.write("			<form action=\"./join.do\" method=\"post\" class=\"appForm\">\r\n");
      out.write("				<fieldset>\r\n");
      out.write("					<legend>상담문의 입력 양식</legend>\r\n");
      out.write("					<p class=\"info_pilsoo pilsoo_item\">필수입력</p>\r\n");
      out.write("					<ul class=\"app_list\">\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("                            <label for=\"email_lbl\" class=\"tit_lbl pilsoo_item\">이메일</label>\r\n");
      out.write("                            <div class=\"app_content email_area\">\r\n");
      out.write("                                <input type=\"text\" class=\"w160\" name=\"id\" id=\"email_lbl\" title=\"이메일 주소\" />\r\n");
      out.write("                                <span class=\"ico_space\">@</span>\r\n");
      out.write("                                <input type=\"text\" class=\"w160\" name=\"email\" title=\"이메일 제공업체 입력\" />										\r\n");
      out.write("                                <div class=\"select_common\">\r\n");
      out.write("                                    <select title=\"이메일 제공업체 목록\">\r\n");
      out.write("                                        <option value=\"\">직접입력</option>\r\n");
      out.write("                                        <option value=\"\">naver.com</option>\r\n");
      out.write("                                        <option value=\"\">hanmail.net</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>										\r\n");
      out.write("                            </div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"name_lbl\" class=\"tit_lbl pilsoo_item\">작성자명</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"text\" name=\"name\" class=\"w100p\" id=\"name_lbl\" placeholder=\"이름을 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"pwd_lbl\" class=\"tit_lbl pilsoo_item\">비밀번호</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"password\" name=\"password\" class=\"w100p\" id=\"pwd_lbl\" placeholder=\"비밀번호를 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"pwd2_lbl\" class=\"tit_lbl pilsoo_item\">비밀번호 확인</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"password\" class=\"w100p\" id=\"pwd2_lbl\" placeholder=\"비밀번호를 다시 한번 입력해주세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"phone_lbl\" class=\"tit_lbl pilsoo_item\">연락처</label>\r\n");
      out.write("							<div class=\"app_content\"><input type=\"tel\" name=\"phone\" class=\"w100p\" id=\"phone_lbl\" placeholder=\"휴대폰”-”없이 숫자만 입력하세요\"/></div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<span class=\"tit_lbl\">성별</span>\r\n");
      out.write("							<div class=\"app_content radio_area\">\r\n");
      out.write("								<input type=\"radio\" class=\"css-radio\" id=\"mmm_lbl\" name=\"gender\" value=\"male\"><label for=\"mmm_lbl\">남</label>\r\n");
      out.write("								<input type=\"radio\" class=\"css-radio\" id=\"www_lbl\" name=\"gender\" value=\"female\"><label for=\"www_lbl\">여</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("                            <span class=\"tit_lbl\">개인정보 활용동의</span>\r\n");
      out.write("							<div class=\"app_content checkbox_area\">\r\n");
      out.write("								<input type=\"checkbox\" class=\"css-checkbox\" id=\"agree_lbl\" name=\"agree\"><label for=\"agree_lbl\">동의함</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"clear\">\r\n");
      out.write("							<label for=\"content_lbl\" class=\"tit_lbl\">문의내용</label>\r\n");
      out.write("							<div class=\"app_content\"><textarea id=\"content_lbl\" name=\"content\" class=\"w100p\" placeholder=\"간단한 상담 요청 사항을 남겨주시면 보다 상세한 상담이 가능합니다.\r\n");
      out.write("전화 상담 희망시 기재 부탁드립니다.\"></textarea></div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p class=\"btn_line\"><button class=\"btn_baseColor\">등록</button></p>	\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("			<!-- //appForm -->\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //bodytext_area -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"foot_area box_inner\">\r\n");
      out.write("			<ul class=\"foot_list clear\">\r\n");
      out.write("				<li><a href=\"javascript;\">이용약관</a></li>\r\n");
      out.write("				<li><a href=\"javascript;\">개인정보취급방침</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<h2>투어리스트인투어</h2>\r\n");
      out.write("			<p class=\"addr\">서울특별시 종로구 혜화동 9길 청운빌딩 5층 <span class=\"gubun\">/</span>        \r\n");
      out.write("				<span class=\"br_line\">대표전화 <span class=\"space0\">02-1234-5678</span> <span class=\"gubun\">/</span>        \r\n");
      out.write("					<span class=\"br_line\">E-mail : <span class=\"space0\"> titour@touristintour.com</span></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p class=\"copy box_inner\">Copyright(c) TouristInTour all right reserved</p>\r\n");
      out.write("			<ul class=\"snslink clear\">\r\n");
      out.write("				<li><a href=\"javascript:;\">blog</a></li>\r\n");
      out.write("				<li><a href=\"javascript:;\">facebook</a></li>\r\n");
      out.write("				<li><a href=\"javascript:;\">instargram</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrap -->\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"hdd\">빠른 링크 : 전화 문의, 카카오톡, 오시는 길, 꼭대기로</h2>\r\n");
      out.write("<div class=\"quick_area\">\r\n");
      out.write("	<ul class=\"quick_list\">\r\n");
      out.write("		<li><a href=\"tel:010-7184-4403\"><h3>전화 문의</h3><p>010-1234-5678</p></a></li>\r\n");
      out.write("		<li><a href=\"javascript:;\"><h3>카카오톡 <em>상담</em></h3><p>1:1상담</p></a></li>\r\n");
      out.write("		<li><a href=\"javascript:;\"><h3 class=\"to_contact\">오시는 길</h3></a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<p class=\"to_top\"><a href=\"#layout0\" class=\"s_point\">TOP</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
